theme = "oceanic-zen"
title = "Hihaheho Studio"
description = "Hihaheho Studio's blog"
default_language = "en"
taxonomies = []
base_url = "https://blog.hihaheho.com"
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
render_emoji = true
external_links_target_blank = true

[extra]
author = "Hihaheho Studio"
